### ISSUE TITLE
npm i trackmania-api-node is not up-to-date

### ISSUE THREAD

**Issue by Sigeth** [breeku/trackmania-api-node#29]
-   **I'm submitting a ...**
    [ ] bug report
    or
    [ ] question about how to use this project

-   **Summary**
When I do npm i trackmania-api-node, it says to me that everything is up to date but doesn't update, so matchmaking can't be accessed.

-   **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by breeku** [comment]
Hello,

Try ```npm update```

 [https://docs.npmjs.com/updating-packages-downloaded-from-the-registry](https://docs.npmjs.com/updating-packages-downloaded-from-the-registry)

**Comment by Sigeth** [comment]
Hello,
I tried what you've said and it's not in `npm outdated` anymore, but I still can't access to `getMatchmakingRanks`

Anyway, thanks for helping me :D

**Comment by breeku** [comment]
```npm i trackmania-api-node@latest``` should work. 

ah, as ```npm update``` depends on the semver you install the package with so if it doesn't have one the command will do nothing. You can see this with ```npm update --dd```. My b
[https://stackoverflow.com/a/25861938/9785691](https://stackoverflow.com/a/25861938/9785691)

The more you know :d

**Comment by Sigeth** [comment]
Ok thanks a lot for your help it works now !
